#!/bin/sh
/usr/bin/purple-remote "setstatus?status=available&message=off-duty"
xmodmap -e 'pointer = 1 2 3 4 5 6 7 8 9 10 11 12 13'
~/usr/bin/disper -s
~/usr/bin/u
adb kill-server
/usr/bin/hamster-cli stop
/usr/bin/purple-remote "quit"
~/usr/bin/xwarppointer abspos 0 0
#dbus-send --system --print-reply --dest="org.freedesktop.Hal" /org/freedesktop/Hal/devices/computer org.freedesktop.Hal.Device.SystemPowerManagement.Hibernate
xfce4-session-logout --hibernate
