#!/usr/bin/env python
# - coding: utf-8 -
#Accepts input like
#[tag[/tag[...]]]][/description.]

import subprocess
import sys, os

# key is hamster category, values are hamster acitivities
fact_dict = {
    'rd':['doc', 'meeting'],
    'test':['testing', 'testdev'],
    'dev':['coding','debugging', 'review', 'scm'],
    'plan':['emails', 'conference', 'weekly'],
    'admin':['it', 'townhall', 'training', 'paperwork'],
    'away':['dining','break','workout'],
    'blogging':['techwrite', 'weibo'],
    'relax':['interrupt','rss'],
    'config':['linux','emacs','windows'],
}

auto_categories = {
    'work': ['rd', 'test', 'dev', 'plan', 'admin'],
    'personal': ['blogging', 'play', 'config', 'relax']
}

purple_status = {
    'rd':'unavailable',
    'meeting': 'unavailable',
    'test':'unavailable',
    'dev':'unavailable',
    'plan':'unavailable',
    'admin':'away',
    'away':'away',
    'break':'available',
    'blogging':'available',
    'relax':'available',
    'config':'unavailable',
    }

category = ''
tags = []
desc = ""

if len(sys.argv) == 2:
    params = sys.argv[1].strip().split("/")
    if params[-1].endswith("."):
        desc = params[-1]
        params = params[:-1]
    if len(params):
        tags = params

activity = os.path.basename(sys.argv[0]).split("_")[1]
fact = 'unknown'
for tmp in fact_dict.keys():
    if activity in fact_dict[tmp]:
        fact = tmp
        break

for tmp in auto_categories.keys():
    if fact in auto_categories[tmp]:
        category = tmp
        break;
if len(category):
    tags.append(category)

status = "away"
if activity in purple_status.keys():
    status = purple_status[activity]
elif fact in purple_status.keys():
    status = purple_status[fact]

hamster_command = "/usr/bin/hamster-cli start \"%s@%s"\
    %(activity, fact)

if desc:
    hamster_command = "%s, %s" %(hamster_command, desc[:-1])
    pidgin_command = "/usr/bin/purple-remote \"setstatus?status=%s&message=%s: %s\""\
        %(status, activity, desc[:-1])
else:
    hamster_command = "%s, " %hamster_command
    pidgin_command = "/usr/bin/purple-remote \"setstatus?status=%s&message=%s\""\
                     %(status, activity)

if tags:
    final_tags = ''
    for tag in tags:
        final_tags = '%s#%s'%(final_tags,tag)

    hamster_command = "%s %s"%(hamster_command, final_tags)

hamster_command = "%s\""%hamster_command

print "hamster command is %s"%hamster_command
print "purple command is %s"%pidgin_command

subprocess.call(hamster_command, shell=True)
subprocess.call(pidgin_command, shell=True)
