#!/bin/sh
# Needs afuse, sshfs
mount_fuse() {
    REMOTEDIR=$1
    MNTDIR=$2
    ACCOUNT=$3

    FUSEDIR=".fuse"

    # sanity check user
    if [ !$ACCOUNT ]; then
        ACCOUNT="$USER"
    fi

    # first check if the target is already mounted
    grep $HOME/$FUSEDIR/$MNTDIR /etc/mtab >/dev/null 2>&1
    STATUS=$?

    if [ $STATUS -eq 0 ]; then
        echo "$HOME/$FUSEDIR/$MNTDIR is already mounted"
    else
    # mount it 
        afuse \
            -o mount_template="sshfs -o workaround=rename $ACCOUNT\@%r:$REMOTEDIR %m" \
            -o unmount_template="fusermount -u -z %m" \
            ~/$FUSEDIR/$MNTDIR
    fi
}

#mount_fuse /localrepo/a22543 localrepo
#mount_fuse /home/a22543 kernelbsp

#ls -l ${HOME}/.fuse/localrepo/ilclbld08.mot.com
#ls -l ${HOME}/.fuse/kernelbsp/wolfenstein.mot.com

#bindfs ${HOME}/.fuse/localrepo/ilclbld08.mot.com ${HOME}/localrepo

#if [ ! -d ${HOME}/remote/kernelbsp ]; then
#    ln -s ${HOME}/.fuse/kernelbsp/wolfenstein.mot.com ${HOME}/remote/kernelbsp
#fi

#smbnetfs ${HOME}/.smb/mnt
#ls ${HOME}/.smb/mnt/samba01.mot.com/il427lnxdroid08/a22543
#bindfs ${HOME}/.smb/mnt/samba01.mot.com/il427lnxdroid08/a22543 ${HOME}/localrepo

sshfs ${USER}@ilclbld08.mot.com:/localrepo/a22543 ${HOME}/localrepo
