#!/bin/sh
/usr/bin/purple-remote "quit"
xmodmap -e 'pointer = 1 2 3 4 5 6 7 8 9 10 11 12 13'
/usr/local/sbin/setproxy off
~/usr/bin/disper -s
~/usr/bin/u
adb kill-server
dbus-send --system --print-reply --dest="org.freedesktop.Hal" /org/freedesktop/Hal/devices/computer org.freedesktop.Hal.Device.SystemPowerManagement.Hibernate
