#!/bin/sh
#~/usr/bin/disper -r 1920x1080 -d DFP-1,DFP-0 -e -t right
sh ~/usr/bin/keymap.sh
xrandr --output HDMI3 --auto --pos 0x0 --output LVDS1 --auto --right-of HDMI3
~/usr/bin/m &
#/usr/bin/pidgin &
#~/usr/bin/kk_emails
#/usr/bin/purple-remote "setstatus?status=available&message=email"
alias localrepo="ssh -X a22543@ilclbld38.mot.com"
xset -b
