#!/bin/bash
#++++++++++++++++
# Monitor Switch
#
# Moves currently focused window from one monitor to the other.
# Designed for a system with two monitors.
# Script should be triggered using a keyboard shortcut.
#++++++++++++++++
# width of left monitor
w_l_monitor=1920

moving_window(){
# get active window position and width
    obj=$1
    x=`xwininfo -id $obj | grep "Absolute upper-left X" | awk '{print $4}'`
    y_abs=`xwininfo -id $obj | grep "Absolute upper-left Y" | awk '{print $4}'`
    y_rel=`xwininfo -id $obj | grep "Relative upper-left Y" | awk '{print $4}'`
    w=`xwininfo -id $obj | grep "Width" | awk '{print $2}'`

# unmaximize
    wmctrl -i -r $obj -b remove,maximized_vert,maximized_horz

# calculate new x position
    if [ "$x" -lt "$w_l_monitor" ]; then
	# window on left monitor
	    new_x=$(($x+$w_l_monitor))
#move window. Need to subtract the relative y-position.
        new_y=$(($y_abs-$y_rel))
        xdotool windowmove $obj $new_x $new_y
    fi

    if [ "$w" -eq "$w_l_monitor" ]; then
	# maximize
	    wmctrl -i -r $obj -b add,maximized_vert,maximized_horz
    fi

}

window_key=`zenity --entry --text "(E)macs,(T)erm,(F)irefox, (M)ind or (C)alc?"`

if [ -z window_key ];then
    return
fi

moving=0

case "$window_key" in
    "t")
        window_name='\<Terminal -'
        ;;
    "e")
        window_name='\<Emacs -'
        ;;
    "f")
        window_name='Pentadactyl$'
        ;;
    "c")
        window_name='\<galculator'
        ;;
    "m")
        window_name=' Freeplane '
        ;;
    "t")
        window_name='\<Terminal -'
        ;;
    "E")
        window_name='\<Emacs -'
        moving=1
        ;;
    "F")
        window_name='Pentadactyl$'
        moving=1
        ;;
    "C")
        window_name='\<galculator'
        moving=1
        ;;
    "M")
        window_name=' Freeplane '
        moving=1
        ;;
    "T")
        window_name='\<Terminal -'
        moving=1
        ;;
    ";")
        window_name='move'
        ~/usr/bin/movewindow
        exit 0
        ;;
esac

if [ -z window_name ]; then
    return
fi

window=`wmctrl -l | egrep $window_name | head -n 1 | cut -f 1 -d " "`
if [ -z $window ]; then
    exit 0
fi
#echo "window id is [$window]"

if [ $moving = 1 ]
then
    moving_window $window
fi

wmctrl -i -R $window
