#!/bin/bash
#++++++++++++++++
# Monitor Switch
#
# Moves currently focused window from one monitor to the other.
# Designed for a system with two monitors.
# Script should be triggered using a keyboard shortcut.
#++++++++++++++++
# width of left monitor
w_l_monitor=1920

moving_window_right(){
# get active window position and width
    obj=$1
    x=`xwininfo -id $obj | grep "Absolute upper-left X" | awk '{print $4}'`
    y_abs=`xwininfo -id $obj | grep "Absolute upper-left Y" | awk '{print $4}'`
    y_rel=`xwininfo -id $obj | grep "Relative upper-left Y" | awk '{print $4}'`
    w=`xwininfo -id $obj | grep "Width" | awk '{print $2}'`

# unmaximize
    wmctrl -i -r $obj -b remove,maximized_vert,maximized_horz

# calculate new x position
    if [ "$x" -lt "$w_l_monitor" ]; then
	# window on left monitor, then moving it right
	    new_x=$(($x+$w_l_monitor))
#move window. Need to subtract the relative y-position.
        new_y=$(($y_abs-$y_rel))
        xdotool windowmove $obj $new_x $new_y
    fi

    if [ "$w" -eq "$w_l_monitor" ]; then
	# maximize
	    wmctrl -i -r $obj -b add,maximized_vert,maximized_horz
    fi

}

moving_window_left(){
# get active window position and width
    obj=$1
    x=`xwininfo -id $obj | grep "Absolute upper-left X" | awk '{print $4}'`
    y_abs=`xwininfo -id $obj | grep "Absolute upper-left Y" | awk '{print $4}'`
    y_rel=`xwininfo -id $obj | grep "Relative upper-left Y" | awk '{print $4}'`
    w=`xwininfo -id $obj | grep "Width" | awk '{print $2}'`

# unmaximize
    wmctrl -i -r $obj -b remove,maximized_vert,maximized_horz

# calculate new x position
    if [ "$x" -ge "$w_l_monitor" ]; then
	# window on right monitor
	    new_x=$(($x-$w_l_monitor))
#move window. Need to subtract the relative y-position.
        new_y=$(($y_abs-$y_rel))
        xdotool windowmove $obj $new_x $new_y
    fi

    if [ "$w" -eq "$w_l_monitor" ]; then
	# maximize
	    wmctrl -i -r $obj -b add,maximized_vert,maximized_horz
    fi

}

window_key=`zenity --entry --text "(E)macs,(T)erm,(F)irefox, (M)ind or (C)alc?"`

if [ -z $window_key ];then
    exit 0
fi

left=0

case "$window_key" in
    "t")
        window_name='\<Terminal -'
        ;;
    "e")
        window_name="\<Emacs - "
        ;;
    "f")
        window_name='Vimperator$'
        ;;
    "c")
        window_name='\<Qalculate!'
        ;;
    "m")
        window_name='\<VYM - View Your Mind'
        ;;
    "t")
        window_name='\<Terminal -'
        ;;
    "E")
        window_name="\<Emacs - "
        left=1
        ;;
    "F")
        window_name='Vimperator$'
        left=1
        ;;
    "C")
        window_name='\<Qalculate!'
        left=1
        ;;
    "M")
        window_name='\<VYM - View Your Mind'
        left=1
        ;;
    "T")
        window_name='\<Terminal -'
        left=1
        ;;
    "*")
        exit 0
        ;;
esac

if [ -z $window_name ]; then
    return
fi

#echo "window name is : $window_name"
window=`wmctrl -l | grep "$window_name" | head -n 1 | cut -f 1 -d " "`
#echo "window nuber is: $window"
if [ -z $window ]; then
    exit 0
fi
#echo "window id is [$window]"

if [ $left = 1 ]
then
    moving_window_left $window
else
#    active_window=`xdotool getactivewindow`
#    moving_window_left $active_window
    moving_window_right $window
fi

wmctrl -i -R $window
