#!/bin/sh
rm ${HOME}/localrepo
rm ${HOME}/remote/kernelbsp
#rm ${HOME}/remote/pmdashboard

fusermount -u -z ${HOME}/.fuse/localrepo
fusermount -u -z ${HOME}/.fuse/kernelbsp
#fusermount -u -z ${HOME}/.fuse/pmdashboard

